name: upload artifacts and use them in other step
on: [push]
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v4
   - name: cache dependencies
     id: cache
     uses: actions/cache@v4
     with:
      path: ~/.npm
      key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
   - name: install dependencies
     if: ${{ steps.cache.outputs.cache-hit!= 'true' }}
     run: npm ci
   - name: test code
     id: test-code
     run: npm test
   - name: upload test artifact
     if: failure() && steps.test-code.outcome=='failure'
     uses: actions/upload-artifact@v4
     with: 
       name: test-report
       path: test

 build:
  runs-on: ubuntu-latest
  needs: test
  steps:
   - name: checkout code
     uses: actions/checkout@v4
   - name: cache dependencies
     id: cache
     uses: actions/cache@v4
     with:
      path: ~/.npm
      key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
   - name: install dependencies
     if: ${{ steps.cache.outputs.cache-hit!= 'true'
     run: npm ci
   - name: build code
     id: build-code
     run: npm run build
   - name: upload test artifact
     if: failure() && steps.test-code.outcome=='failure'
     uses: actions/upload-artifact@v4
     with: 
       name: build-report
       path: build
 deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-report
      - name: Output contents
        run: ls  
  
  

 
      
