name: upload artifacts and use them in other job
on: [push]
jobs:
 test:
  runs-on: ubuntu-latest
  continue-on-error: true
  steps:
   - name: checkout code
     uses: actions/checkout@v3
   - name: cache dependencies
     id: cache
     uses: actions/cache@v4
     with:
      path: ~/.npm
      key: node-modules-${{ hashFiles('**/package-lock.json') }}
   - name: install dependencies
    # if: ${{ steps.cache.outputs.cache-hit!= 'true' }}
     run: npm ci
   - name: test code
     id: test-code
     run: npm run test
   - name: upload test artifact
     if: failure() && steps.test-code.outcome=='failure'
     uses: actions/upload-artifact@v3
     with: 
       name: test-report
       path: test

 build:
  runs-on: ubuntu-latest
  needs: test
  continue-on-error: true
  steps:
   - name: checkout code
     uses: actions/checkout@v3
   - name: cache dependencies
     id: cache
     uses: actions/cache@v3
     with:
      path: ~/.npm
      key: node-modules-${{ hashFiles('**/package-lock.json') }}
   - name: install dependencies
#     if: ${{ steps.cache.outputs.cache-hit!= 'true' }}
     run: npm ci
   - name: build code
     id: build-code
     run: npm run build
   - name: upload build artifact
     if: failure() && steps.build-code.outcome =='failure'
     uses: actions/upload-artifact@v3
     with: 
       name: build-report
       path: build
 deploy:
  runs-on: ubuntu-latest
  needs: build
  continue-on-error: true
  steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-report
      - name: Output contents
        run: ls  
  
  

 
      
