name: Matrix Demo
on: push
jobs:
 build: 
   continue-on-error: true # on job level continue-on-error tells github actions to continue executing the jobs that
   # are related to the matrix even if some jobs or some combinations fail.
   strategy:
     matrix:
       node-version: [ 12 , 14, 16]
       operating-system: [ ubuntu-latest, window-latest]
       exclude:
          - node-version: 12
            operating-system: window-latest
          - node-version: 14
            operating-system: window-latest
   runs-on: ${{ matrix.operating-system }}
   steps:
     - name: get code
       uses: actions/checkout@v4
     - name: install nodejs
       uses: actions/setup-node@v4
       with: 
           node-version: ${{  matrix.node-version }}
     - name: Install dependencies
       run: npm ci
     - name: Build project
       run: npm run build
