name: reusable workflow

on: 
  workflow_call:

   inputs:                      
     artifact-name: 
       description: "The name of the deployable artifacts"
       required: false  # If true, this workflow needs the input value to run; otherwise, it will fail.
       default: dist    # The default artifact name if no input is provided.
       type: string     # Expected type of the input value.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }} # Uses the input value for artifact name.

      - name: List files
        run: ls

      - name: Output info
        run: echo "Deploying"
