name: reusable workflow

on: 
  workflow_call:

   inputs:                    # pass inputs to this resusable workflow.
   #This declares inputs for the reusable workflow.
   #Any workflow that calls this reusable workflow can provide these inputs.
     artifact-name: 
       description: "The name of the deployable artifacts"
       required: false  # Controls whether this input is mandatory:
#true → The workflow must receive a value, or it will fail.
#false → The workflow can run without this input (it will use a default if not provided).
       default: dist    # The default artifact name if no input is provided.
#Sets a default value (dist) if no input is provided.
#If the calling workflow doesn’t specify artifact-name, it automatically assumes "dist".
       type: string     # Expected type of the input value.
       #Specifies the data type expected for this input.
      # In this case, it should be a string (text value).
   outputs:
    result: 
      description: the result of the deployment operation.
      value: ${{ jobs.deploy}}
   
   # secrets:                  
   # some-secret: 
     # required: false 
jobs:
  deploy:
   outputs: 
    outcome: ${{ steps.set-result.outputs.step-result}}
   runs-on: ubuntu-latest
   steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }} # Uses the input value for artifact name.
          #This dynamically assigns the value of artifact-name input to the name field.
       #The ${{ inputs.artifact-name }} is a GitHub Actions expression, which pulls the value of the input provided to the workflow.

      - name: List files
        run: ls

      - name: Output info
        run: echo "Deploying"
      - name: set result output
        id : set-result
        run: echo " ::set-output=step-result::success"
