name: Caching and Artifacts
on: [workflow_dispatch]
jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: "npm-cache"
      - name: Display Cache Output
        run: echo '${{ toJSON(steps.cache-dependencies.outputs) }}'
      - name: Install dependencies
        run: npm install
  
